#!/usr/bin/env bash
# Turn a scan into a report a human will actually read: grouped by owner,
# because "who do I talk to" is the question that decides whether anything
# happens, and no dashboard answers it.
#
# Writes Markdown to stdout. Pipe it into an email, a PR comment, a Slack
# webhook, or a wiki page.
#
#   ./examples/weekly-digest.sh > digest.md
#   PROMETHEUS=http://prom:9090 ./examples/weekly-digest.sh | \
#     curl -X POST -H 'Content-type: application/json' \
#          --data @- "$SLACK_WEBHOOK_URL"   # after shaping it as Slack JSON
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ULLAGE="${ULLAGE:-$ROOT/bin/ullage}"

command -v jq >/dev/null || { echo "this example needs jq" >&2; exit 2; }
[ -x "$ULLAGE" ] || (cd "$ROOT" && make build >/dev/null)

# An array, not a string: unquoted ${VAR:+...} word-splits, and Go's flag
# package stops at the first non-flag argument, so a stray word would silently
# swallow --output json and hand jq a page of human-readable text.
args=()
if [ -n "${PROMETHEUS:-}" ]; then
  args+=(--prometheus "$PROMETHEUS")
else
  args+=(demo)
fi

report="$("$ULLAGE" "${args[@]}" --output json --exit-zero 2>/dev/null)" || {
  echo "ullage could not complete a scan; run \`ullage doctor\`" >&2
  exit 2
}

jq -r '
  def money: if . == null then "—" else "$" + (. | floor | tostring) end;

  # The wire format is ISO-8601 because it is unambiguous; a report for humans
  # should not be.
  def humanDuration:
    (capture("P(?<d>[0-9]+)D")? // null) as $m
    | if $m then "\($m.d)d" else . end;

  "# Idle accelerator report",
  "",
  "Window: \(.scan.window | humanDuration), ending \(.scan.started[0:10]). Cluster: `\(.scan.context)`.",
  "",
  "**\(.scan.gpuHoursUnused | floor) of \(.scan.gpuHoursPaid | floor) accelerator-hours "
  # The // operator catches null, not zero, and a cluster with no analysable
  # accelerators reports zero paid hours -- so guard the divisor explicitly
  # or the whole digest dies with a division error.
  + "did no work** (\(if (.scan.gpuHoursPaid // 0) > 0
                       then (.scan.gpuHoursUnused / .scan.gpuHoursPaid * 100 | floor)
                       else 0 end)%), "
  + "across \(.scan.acceleratorsAnalyzed) of \(.scan.acceleratorsObserved) accelerators analysed.",
  "",

  # Grouped by owner. An unowned finding is called out rather than hidden,
  # because "nobody is responsible for this" is itself the finding.
  (if (.recommendations | length) == 0 then
     "No idle accelerators above the reporting threshold. Nothing to do."
   else
     ["## By owner", ""] +
     ( .recommendations
       | group_by(.owner.identity // "unowned")
       | sort_by(-([.[].impact.windowCost // 0] | add))
       | map(
           "### \(.[0].owner.identity // "_unowned_") — \([.[].impact.windowCost // 0] | add | money)",
           "",
           ( .[] | "- **\(.id)** — \(.impact.gpuHoursUnused | floor) accelerator-hours, "
                 + "\(.impact.windowCost | money)  \n"
                 + "  \(.summary)  \n"
                 + (if .fix.command and .fix.command != ""
                    then "  ```\n  \(.fix.command)\n  ```"
                    else "  _No safe automatic fix. \(.fix.rationale // "The owner must decide.")_"
                    end) ),
           ""
         )
       | flatten
     ) | .[]
   end),

  # Everything the report is not claiming. A percentage over a denominator the
  # reader cannot account for is how a monitoring gap becomes an argument.
  (if (.byDesign | length) > 0 then
     "## Held on purpose",
     "",
     "Not counted as waste, listed so the decision stays visible:",
     "",
     (.byDesign[] | "- \(.id) — \(.summary)"),
     ""
   else empty end),

  (if (.notAnalyzed | length) > 0 then
     "## Not analysed",
     "",
     (.notAnalyzed[] | "- \(.accelerators) accelerators — \(.reason): \(.detail)"),
     ""
   else empty end),

  (if (.warnings | length) > 0 then
     "## Caveats", "", (.warnings[] | "- \(.)"), ""
   else empty end),

  "---",
  "_Generated by [ullage](https://github.com/ganeshkumarashok/ullage) \(.scan.tool.version). "
  + "Costs are approximate list prices. Reply to this report rather than acting silently: "
  + "`ullage explain <id>` shows the full evidence for any line above._"
' <<<"$report"
